# -*- coding: utf-8 -*-
"""homework-7-apollonov.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JFvAg-1zIKmdAe3Rzpm1Cr8E_2ESw0X5

Задание 7 (работа с файлами)  
Напишите функцию, которая принимает в качестве аргументов два пути
- in_file
- out_file  
в файле (in_file) содержатся данные о продуктах (название, цена, количество)
построчно через пробел  
ПРИМЕР:  
велосипед 45000 5  
ролики 13000 10  
out_file это путь до файла, который должна сгенерировать ваша программа  
1 уровень сложности  
функция должна преобразовать данные из in_file в список словарей и записать
в out_file  
2 уровень сложности  
программа должна дополнительно дедуплицировать товары. Если встречаются
две строчки с велосипедами в итоговом файле должна быть одна строчка с
суммарным количеством и наименьшей ценой среди велосипедов  
ПРИМЕР:  
велосипед 45000 5  
велосипед 35000 15  
велосипед 55000 5  
{  
"title": "велосипед",  
"price": 35000,  
"count": 25  
}

## Ввод файла текстового
"""

import json

#  файлы формируются во временной папке collab
# для сохранения на гугл диске, указывать путь /content/drive/MyDrive/...

in_file = 'test_input.txt'
out_file = 'test_output.json'
out_file_total = 'test_output_total.json'

product_txt = '''велосипед 45000 5
самокат 24000 3
самолет 345000 5
велосипед 120 5
самокат 10000 4
самокат 5000 6
сноуборд 12000 6
самокат 50 5'''
with open(in_file, 'w', encoding='utf-8') as f:
    f.write(product_txt)

"""## Задание level 1"""

def transform_txt_json_level_1(in_file, out_file):
  lst_prod = []

  with open(in_file, 'r', encoding='utf-8') as f: 
    for s  in f:
      title, price, count = s.strip().split()
      lst_prod.append({
          "title" : title,
          "price" : int(price),
          "count" : int(count)
      }) 
  with open(out_file, 'w', encoding = 'utf-8') as f:
      f.write(json.dumps(lst_prod, ensure_ascii=False, indent=4))

"""## Задание level 2"""

def transform_txt_json_level_2(in_file, out_file):
  lst_prod = []
  unique_title = set()
  total_prod =[]
  
  with open(in_file, 'r', encoding='utf-8') as f: # считываем построчно и преобразем в поэлементный список
    for s  in f:
      str_prod = s.strip().split()# разбираем на элементы строку без символа конца строки
      unique_title.add(str_prod[0]) # множество уникальных значений title
      lst_prod.append(str_prod) # список строк поэлементный
 
  for prod in unique_title:
    count_sum = 0
    price_lst = []

    for title, price, count in lst_prod:
      if prod == title:
        count_sum += int(count)
        price_lst.append(int(price))

    total_prod.append({
          "title" : prod,
          "price" : min(price_lst),
          "count" : count_sum
      }) 
    
  with open(out_file, 'w', encoding = 'utf-8') as f:
      f.write(json.dumps(total_prod, ensure_ascii=False, indent=4))

transform_txt_json_level_1(in_file, out_file)

transform_txt_json_level_2(in_file, out_file_total)